### ISSUE TITLE
Some data is incorrect

### ISSUE THREAD

**Issue by oznogon** [statsbomb/open-data#1]
Specifically:

- The Orlando Pride are incorrectly referred to as Orlando Pride SC, an error also made on Soccerway and the NWSL website for archived 2016 matches.
- Ryan Williams is listed as being Australian, but she is from the USA and has no reported links to Australia.
- Thaisa's name is misspelled as Thaysa.

For illustrative purposes, detailed changes can be seen in https://github.com/oznogon/open-data/pull/1, but the license on this data appears to preclude directly contributing to it.

**Comment by deepxg** [comment]
Thanks for the report, I'll pass this on to our collection team and get those fixed.

**Comment by deepxg** [comment]
We fixed the player issues a while ago, but I think we have the name right since  fe0ad943e95810f6d61e2b77a5abbf935e49fd44. Thanks!
